### ISSUE TITLE
Remove dependency on the `trinity` package

### ISSUE THREAD

**Issue by spirit-q2** [humanprotocol/hmt-escrow#272]
We have the package only for its dependencies, not for the package itself. What we actually use is `web3==5.12.0` and `py-evm==0.3.0a18`.
Since the `trinity` package is not maintained and its repository archived, there are no benefits of keep using it and it can be replaced with the real dependencies.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200560623420491/1201175417135913) by [Unito](https://www.unito.io)

**Comment by adam-mrozik** [comment]
@spirit-q2 , unfortunately we have a dependency for trinity:
https://github.com/humanprotocol/hmt-escrow/blob/master/hmt_escrow/storage.py#L10

this `p2p` module is available in trinity package

EDIT:
Though `trinity` is archived anyway.
The official package from Ethereum that seem to be doing similar job as the code above is https://github.com/ethereum/pydevp2p
Will see if replacing it 1:1 will work for the CICD

**Comment by adam-mrozik** [comment]
Above package is heavily outdated and conflicts on sub-dependencies (there are issues on github stating the same issue and it has not been touched for 4 years), so it is not an option.


My call would be to take this small p2p crypto script and bring it to ourselves, since it is MIT licence, but I am not sure if this is something we can/want to do.
@e271828- Could you comment if this is the solution we can go with?
